
networks:
  retailflow_network:
    driver: bridge

volumes:
  retailflow_db_volume:
    driver: local
  retailflow_zookeeper_data:
    driver: local
  retailflow_zookeeper_log:
    driver: local
  retailflow_kafka_data:
    driver: local

services:
  postgres:
    image: postgres:15-alpine
    container_name: retailflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - retailflow_db_volume:/var/lib/postgresql/data
    networks:
      - retailflow_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s # Cứ 10 giây hỏi một lần
      timeout: 5s # Đợi 5 giây nếu không trả lời coi như fail
      retries: 5 # Hỏi 5 lần mà fail thì kết luận container đã sập
      start_period: 20s
  # =========================================
  # ZOOKEEPER - Người quản lý cụm (Cluster Manager)
  # =========================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: retailflow_zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - retailflow_zookeeper_data:/var/lib/zookeeper/data
      - retailflow_zookeeper_log:/var/lib/zookeeper/log
    networks:
      - retailflow_network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc -w 2 localhost 2181 | grep imok"]
      interval: 10s 
      timeout: 5s
      retries: 5
      start_period: 20s
  # =========================================
  # KAFKA - Trạm trung chuyển dữ liệu (Message Broker)
  # =========================================
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: retailflow_kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - retailflow_kafka_data:/var/lib/kafka/data
    networks:
      - retailflow_network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s  # Kafka cần thời gian khởi động lâu hơn